name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'   # Change to your required Java version

    - name: Set up Maven
      run: |
        sudo apt-get update
        sudo apt-get install -y maven

    - name: Build with Maven
      run: mvn -f planttycoon/pom.xml clean install  # Adjust the path as needed

    - name: Run tests
      run: mvn -f planttycoon/pom.xml test  # Adjust the path as needed
