name: build-test-deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          
      - name: Install Maven
        run: sudo apt-get install -y maven
        
      - name: Print working directory
        run: pwd
        
      - name: List files in working directory
        run: ls -al
        
      - name: Build with Maven
        working-directory: ./planttycoon  # 'pom.xml' 파일이 있는 경로로 설정
        run: mvn clean install -Dspring.profiles.active=github
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          
      - name: Install Maven
        run: sudo apt-get install -y maven
        
      - name: Print working directory
        run: pwd
        
      - name: List files in working directory
        run: ls -al
        
      - name: Run tests with Maven
        working-directory: ./planttycoon  # 'pom.xml' 파일이 있는 경로로 설정
        run: mvn test -Dspring.profiles.active=github
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
